# Generated by Django 4.2.20 on 2025-03-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='attempts',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
    ]
